### ISSUE TITLE
Server processing unauthorized error

### ISSUE THREAD

**Issue by tdkhl** [lcfidev/star#10]
Hello, what's causing this ?
Could we chat a bit?
![image](https://github.com/user-attachments/assets/63a0d1d9-98ed-417f-bd01-1bc540f2a2c0)

**Comment by lcfidev** [comment]
more context please and if the repo has been edited by you is it a forked one ?

**Comment by tdkhl** [comment]
Could we chat somewhere else ? @lcfidev 

Btw, the ws is sent the way you did, maybe I could send a code snippet

**Comment by lcfidev** [comment]
discord.gg/hasurei
