### ISSUE TITLE
trojan

### ISSUE THREAD

**Issue by Kamiumi** [lcfidev/star#6]
hey whys this showing up in virus protection as a trojan threat all of a sudden? it was working fine yesterday?
![image_2024-08-02_162053259](https://github.com/user-attachments/assets/ecf9b43e-98d9-461d-bc8c-f28777d69249)

**Comment by Kamiumi** [comment]
also happening to all my friends who used it just yesterday after the update

**Comment by lcfidev** [comment]
we are aware of this false positive

**Comment by lcfidev** [comment]
its been fixed download version 1.6.1
